
version: 2.1

jobs:
  say-hello:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: "creating infra"
          command: |
              aws cloudformation deploy \
                --template-file ec2.yml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1

workflows:
  say-hello-workflow:
    jobs:
      - ceate-infra
