version: 2.1

jobs:
  configure-infra:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "5c:81:b9:e8:60:b2:22:32:12:69:7c:fe:05:b3:da:9e"
      - run:
          name: "install ansible"
          command: |
<<<<<<< HEAD
                  apk add --update ansible
      - run:
          name: "Configure server"
          command: |
            ansible-playbook -i inventory.txt main.yml

workflows:
  say-hello-workflow:
    jobs:
      - configure-infra
=======
              aws cloudformation deploy \
                --template-file ec2.yml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1
workflows:
  say-hello-workflow:
    jobs:
      - create-infra
>>>>>>> 80b7804fceb2509f6940b8e003b9c7c405096dd1
