- name: Update repositories cache
  apt:
    update_cache: yes

- name: Upgrade all packages
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes


- name: install dependencies.
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes


- name: Install pm2 globally
  npm:
    name: pm2
    global: yes
    production: yes
    state: present



- name: Create a directory if it does not exist
  file:
    path: ~/web
    state: directory

- name: Copy index.js file to ec2
  template:
    src: "files/index.js"
    dest: "~/web/index.js"

- name: run web server 
  shell: | 
    pm2 start ~/web/index.js -f
